//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAlarmAnalyzer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PGCIL_EVENTS
    {
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Message_Group { get; set; }
        public string Message_Text { get; set; }
        public string WinCC_message_text { get; set; }
        public string Value { get; set; }
        public string Cause { get; set; }
        public string Additional_cause { get; set; }
        public Nullable<double> Duration { get; set; }
        public string Status { get; set; }
        public string Acknowledgment_Status { get; set; }
        public Nullable<int> Number { get; set; }
        public string Class { get; set; }
        public string Type { get; set; }
        public string Point_of_error { get; set; }
        public string Unit { get; set; }
        public Nullable<byte> Value_text_group { get; set; }
        public string Location { get; set; }
        public string Status_Validity { get; set; }
        public string ID_number { get; set; }
        public string Supplementary_Information { get; set; }
        public string T_st { get; set; }
        public Nullable<byte> SICAM_Flag { get; set; }
        public int ID { get; set; }
    }
}
